#!/usr/bin/env python3
"""
Builds the animated header from the Figma spec in hero_layout / hero_motion.

Emits three artefacts:

  public/hero/object-<name>.webp        eight sprites cut from Figma's sheets
  src/components/site/hero/heroSpec.ts  positions, sizes and copy
  src/app/hero-animation.css            @keyframes for all 25 animated nodes

The CSS route was chosen over a runtime animation library: it adds no
dependency, runs without JavaScript, and the existing prefers-reduced-motion
rule in globals.css disables it for free.

Figma gives each node up to five independently-timed tracks (opacity, rotate,
scale, x, y) with per-segment easing. CSS can animate `opacity`, `rotate`,
`scale` and `translate` as separate properties, so four of the five map
across directly, keeping their exact easing. Only `x` and `y` have to share
one `translate` track; where their keyframe times disagree, the merged
segment is sampled into short linear steps so the curve is preserved.

Usage:
    python3 scripts/build-hero-animated.py
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import hero_layout as L            # noqa: E402
import hero_motion as M            # noqa: E402

from PIL import Image              # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SHEETS = os.path.join(ROOT, ".figma-ref", "hero-animated")
WEBP_OUT = os.path.join(ROOT, "public", "hero")
SPEC_OUT = os.path.join(ROOT, "src", "components", "site", "hero", "heroSpec.ts")
CSS_OUT = os.path.join(ROOT, "src", "app", "hero-animation.css")

SCALE = 3          # rasters are cut at 3x for retina
SUBDIV = 8         # linear steps per merged translate segment
PREFIX = "hv"      # keyframe namespace

BANNER = ("/* AUTO-GENERATED by scripts/build-hero-animated.py — "
          "do not edit by hand.\n"
          "   Source: Figma \"Health Verse Revamp_Jan25\", node 1208:3049.\n"
          "   The spec lives in scripts/hero_layout.py and "
          "scripts/hero_motion.py. */\n")


# --------------------------------------------------------------------------
# easing
# --------------------------------------------------------------------------

def bezier_at(points, t):
    """Evaluate a CSS cubic-bezier easing at progress t in [0, 1]."""
    if points is None:
        return t
    x1, y1, x2, y2 = points

    def curve(a1, a2, u):
        return ((1 - u) ** 3 * 0 + 3 * (1 - u) ** 2 * u * a1
                + 3 * (1 - u) * u * u * a2 + u ** 3)

    # Invert x(u) = t by bisection: x is monotonic for valid CSS control
    # points, and 40 halvings land well inside sub-pixel accuracy.
    lo, hi = 0.0, 1.0
    for _ in range(40):
        mid = (lo + hi) / 2
        if curve(x1, x2, mid) < t:
            lo = mid
        else:
            hi = mid
    return curve(y1, y2, (lo + hi) / 2)


def ease_points(ease):
    """Normalise a Figma easing into cubic-bezier control points, or None."""
    if isinstance(ease, str):
        return M.BEZIER[ease]
    return tuple(ease)


def ease_css(ease):
    if isinstance(ease, str):
        return M.EASE_KEYWORDS[ease]
    a, b, c, d = ease
    return f"cubic-bezier({num(a)}, {num(b)}, {num(c)}, {num(d)})"


def segments(track):
    """Yield (t0, t1, v0, v1, ease) for each segment of a track."""
    values, times, eases = track
    if isinstance(eases, str):
        eases = [eases] * (len(times) - 1)
    for i in range(len(times) - 1):
        yield times[i], times[i + 1], values[i], values[i + 1], eases[i]


def sample(track, t):
    """Exact value of a track at time t."""
    values, times, _ = track
    if t <= times[0]:
        return values[0]
    if t >= times[-1]:
        return values[-1]
    for t0, t1, v0, v1, ease in segments(track):
        if t0 <= t <= t1:
            if t1 == t0:
                return v1
            u = (t - t0) / (t1 - t0)
            return v0 + (v1 - v0) * bezier_at(ease_points(ease), u)
    return values[-1]


def close(a, b):
    """Figma's values arrive as decimals that do not survive float maths
    exactly — -10.096 interpolated at u=1 comes back 1e-15 heavier."""
    return abs(a - b) < 1e-9


def track_ease_over(track, t0, t1):
    """How faithfully one track can be drawn across [t0, t1] by a keyframe.

    Returns "flat" when the track holds still, so any easing will do;
    the track's own easing when [t0, t1] is exactly one of its segments;
    and None when the span cuts across a curve and has to be sampled.
    """
    for s0, s1, v0, v1, ease in segments(track):
        if s0 <= t0 and t1 <= s1:
            if close(v0, v1):
                return "flat"
            if close(s0, t0) and close(s1, t1):
                return ease
            return "linear" if ease == "linear" else None
    return None


# --------------------------------------------------------------------------
# formatting
# --------------------------------------------------------------------------

def num(value, places=4):
    """Trim a float to the shortest exact-enough decimal form."""
    text = f"{round(float(value), places):.{places}f}".rstrip("0").rstrip(".")
    return text if text not in ("", "-0") else "0"


def pct(t):
    return f"{num(t * 100)}%"


def keyframes_block(name, frames, declare):
    """Render one @keyframes rule.

    `frames` is a list of (time, value, ease). `declare` turns a value into
    its CSS declarations.
    """
    lines = [f"@keyframes {name} {{"]
    for time, value, ease in frames:
        body = declare(value)
        if ease is not None and ease != "linear":
            body += f" animation-timing-function: {ease_css(ease)};"
        lines.append(f"  {pct(time)} {{ {body} }}")
    lines.append("}")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# track -> keyframes
# --------------------------------------------------------------------------

def simple_frames(track):
    """Keyframes for a track that owns a CSS property outright."""
    values, times, eases = track
    if isinstance(eases, str):
        eases = [eases] * (len(times) - 1)
    frames = [(times[i], values[i], eases[i]) for i in range(len(times) - 1)]
    frames.append((times[-1], values[-1], None))
    return frames


def translate_frames(x_track, y_track):
    """Merge the x and y tracks onto one `translate` timeline.

    Where both tracks have a native segment with the same easing, that
    easing is kept verbatim. Where only one track is really moving, the
    moving track's easing wins. Otherwise the segment is sampled into SUBDIV
    linear steps, which reproduces both curves to within a fraction of a
    pixel.
    """
    if x_track is None:
        x_track = ([0, 0], [0, 1], "linear")
    if y_track is None:
        y_track = ([0, 0], [0, 1], "linear")

    breaks = sorted(set(x_track[1]) | set(y_track[1]))
    frames = []
    for t0, t1 in zip(breaks, breaks[1:]):
        x_ease = track_ease_over(x_track, t0, t1)
        y_ease = track_ease_over(y_track, t0, t1)

        if x_ease == "flat" and y_ease == "flat":
            ease = "linear"
        elif x_ease == "flat":
            ease = y_ease
        elif y_ease == "flat":
            ease = x_ease
        elif x_ease == y_ease:
            ease = x_ease
        else:
            ease = None     # the two curves disagree; sample instead

        if ease is not None:
            frames.append((t0, (sample(x_track, t0), sample(y_track, t0)), ease))
        else:
            for step in range(SUBDIV):
                t = t0 + (t1 - t0) * step / SUBDIV
                frames.append((t, (sample(x_track, t), sample(y_track, t)), "linear"))

    frames.append((breaks[-1],
                   (sample(x_track, breaks[-1]), sample(y_track, breaks[-1])), None))
    return frames


def node_rules(node_id, name, role, props):
    """Return (css_text, animation_shorthand_list) for one animated node."""
    slug = name.lower().replace(" ", "-").replace(".", "-")
    blocks, animations = [], []

    def add(prop_name, frames, declare):
        kf = f"{PREFIX}-{slug}-{prop_name}"
        blocks.append(keyframes_block(kf, frames, declare))
        animations.append(kf)

    if "opacity" in props:
        add("opacity", simple_frames(props["opacity"]),
            lambda v: f"opacity: {num(v)};")

    if "rotate" in props:
        add("rotate", simple_frames(props["rotate"]),
            lambda v: f"rotate: {num(v)}deg;")

    if "scale" in props:
        add("scale", simple_frames(props["scale"]),
            lambda v: f"scale: {num(v)};")

    if "scaleY" in props:
        # Tags squash on Y only. CSS applies rotate before scale, matching
        # Figma, where scaling happens in the node's own rotated space.
        add("scaley", simple_frames(props["scaleY"]),
            lambda v: f"scale: 1 {num(v)};")

    if "x" in props or "y" in props:
        add("translate", translate_frames(props.get("x"), props.get("y")),
            lambda v: f"translate: {num(v[0])}px {num(v[1])}px;")

    header = f"/* {name} — Figma {node_id} ({role}) */"
    return header + "\n" + "\n".join(blocks), slug, animations


# --------------------------------------------------------------------------
# artefacts
# --------------------------------------------------------------------------

def build_sprites():
    sizes = L.icon_render_size()
    rows, total = [], 0
    os.makedirs(WEBP_OUT, exist_ok=True)
    for icon in sorted(L.SPRITES):
        sheet_name = L.SPRITES[icon][0]
        sheet = Image.open(os.path.join(SHEETS, sheet_name)).convert("RGBA")
        x, y, w, h = L.sprite_crop(icon, sheet.width, sheet.height)
        box = (max(0, round(x)), max(0, round(y)),
               min(sheet.width, round(x + w)), min(sheet.height, round(y + h)))
        draw_w, draw_h = sizes[icon]
        target = (round(draw_w * SCALE), round(draw_h * SCALE))
        out = sheet.crop(box).resize(target, Image.LANCZOS)
        path = os.path.join(WEBP_OUT, f"object-{icon}.webp")
        out.save(path, "WEBP", quality=90, method=6)
        kb = os.path.getsize(path) / 1024
        total += kb
        rows.append(f"  object-{icon + '.webp':<18} {target[0]:>3}x{target[1]:<4} "
                    f"{kb:5.1f} KB  from {sheet_name} {box}")
    return rows, total


def build_spec():
    def entry(**kw):
        """Values arrive already in TS form — strings pre-quoted, numbers raw."""
        return "  { " + ", ".join(f"{k}: {v}" for k, v in kw.items()) + " },"

    def n(value):
        """3dp is well below a device pixel; drop a trailing `.0` while there."""
        return f"{round(value, 3):g}"

    def quoted(value):
        return '"' + value.replace('"', '\\"') + '"'

    lines = [
        "// AUTO-GENERATED by scripts/build-hero-animated.py — "
        "do not edit by hand.",
        '// Source: Figma "Health Verse Revamp_Jan25", node 1208:3049 '
        '"Header/ Animated".',
        "//",
        "// Every number is in CSS pixels within the 360x367 frame. Figma's "
        "frame is",
        "// 360x395; the top 28px is a device status bar, which is not "
        "rendered for",
        "// the same reason Header.tsx omits it.",
        "",
        f"export const FRAME_WIDTH = {L.FRAME_WIDTH};",
        f"export const FRAME_HEIGHT = {L.FRAME_HEIGHT};",
        f"export const LOOP_SECONDS = {M.LOOP_SECONDS};",
        "",
        "/** Figma: brand-blue/Gradients - Brand/Dark/900 -> 700 (45deg). */",
        "export const BACKGROUND =",
        f'  "linear-gradient({L.BACKGROUND["angle"]}deg in srgb, '
        f'{L.BACKGROUND["from"][1]} 0%, {L.BACKGROUND["to"][1]} 100%)";',
        "",
    ]

    rx, ry, rw, rh = L.place(L.RING["box"])
    lines += [
        "export const RING = {",
        f"  left: {n(rx)}, top: {n(ry)}, size: {n(rw)},",
        f"  outer: {{ r: {L.RING['outer']['r']}, "
        f"width: {L.RING['outer']['stroke_width']}, "
        f"opacity: {L.RING['outer']['opacity']} }},",
        f"  inner: {{ r: {L.RING['inner']['r']}, "
        f"width: {L.RING['inner']['stroke_width']}, "
        f"opacity: {L.RING['inner']['opacity']} }},",
        f"  dot: {{ cx: {L.RING['dot']['cx']}, cy: {L.RING['dot']['cy']}, "
        f"r: {L.RING['dot']['r']}, opacity: {L.RING['dot']['opacity']} }},",
        "} as const;",
        "",
    ]
    assert abs(rw - rh) < 1e-6, "ring must be square"

    bx, by, bw, _bh = L.place(L.BADGE["box"])
    lines += [
        "export const BADGE = {",
        f"  left: {n(bx)}, top: {n(by)}, width: {n(bw)},",
        f"  iconSize: {L.BADGE['icon_size']}, gap: {L.BADGE['gap']},",
        f"  text: {quoted(L.BADGE['text'])},",
        "} as const;",
        "",
    ]

    hx, hy, hw, _hh = L.place(L.HERO_WORD["box"])
    lines += [
        "export const HERO_WORD = {",
        f"  left: {n(hx)}, top: {n(hy)}, width: {n(hw)},",
        f"  text: {quoted(L.HERO_WORD['text'])},",
        f"  shadow: {quoted(L.HERO_WORD['shadow'])},",
        "} as const;",
        "",
        "export type HeroTag = {",
        "  id: string; text: string; token: string;",
        "  left: number; top: number; width: number; height: number;",
        "};",
        "",
        f"/** All four are rotated {L.TAG_ROTATION} degrees in Figma. */",
        f"export const TAG_ROTATION = {L.TAG_ROTATION};",
        "",
        "export const TAGS: HeroTag[] = [",
    ]
    for tag in L.TAGS:
        x, y, w, h = L.place(tag["box"], L.TAG_ROTATION)
        lines.append(entry(id=quoted(tag["id"]), text=quoted(tag["text"]),
                           token=quoted(tag["token"]),
                           left=n(x), top=n(y), width=n(w), height=n(h)))
    lines += [
        "];",
        "",
        "export type HeroProof = {",
        "  id: string; text: string;",
        "  left: number; top: number; width: number;",
        "};",
        "",
        "export const PROOFS: HeroProof[] = [",
    ]
    for proof in L.PROOFS:
        x, y, w, _h = L.place(proof["box"])
        lines.append(entry(id=quoted(proof["id"]), text=quoted(proof["text"]),
                           left=n(x), top=n(y), width=n(w)))
    lines += [
        "];",
        "",
        "export type HeroObject = {",
        "  id: string; icon: string;",
        "  left: number; top: number; width: number; height: number;",
        "};",
        "",
        "/** Listed back-to-front, which is also the order they render in. */",
        "export const OBJECTS: HeroObject[] = [",
    ]
    for obj in L.OBJECTS:
        x, y, w, h = L.place(obj["box"], obj["rest_rotation"])
        lines.append(entry(id=quoted(obj["id"]), icon=quoted(obj["icon"]),
                           left=n(x), top=n(y), width=n(w), height=n(h)))
    lines.append("];")
    return "\n".join(lines) + "\n"


REST_ROTATION = {obj["node"]: obj["rest_rotation"] for obj in L.OBJECTS}


def phase_of(name):
    """Which quarter of the loop a node belongs to, or None for the ring."""
    if name.startswith("object"):
        return int(name[len("object")])
    if name.startswith(("tag ", "proof ")):
        return int(name.split()[1])
    return None


def still_declarations(node_id, name, role, props):
    """The node's appearance in Figma's own static render of the frame.

    That render shows phase 1 only, with every node at its canvas position
    and rest rotation, so the values come from the layout spec rather than
    from the timeline. Freezing the timeline instead would catch the objects
    mid-bob — they never fully stop — and would leak object3.1, whose
    opacity track dips across the whole first half of the loop.
    """
    if role == "ring":
        return ["rotate: 0deg;"]
    if phase_of(name) != 1:
        return ["opacity: 0;"]

    out = ["opacity: 1;"]
    if "rotate" in props:
        out.append(f"rotate: {num(REST_ROTATION[node_id])}deg;")
    if "scale" in props:
        out.append("scale: 1;")
    if "scaleY" in props:
        out.append("scale: 1 1;")
    if "x" in props or "y" in props:
        out.append("translate: 0px 0px;")
    return out


def build_css():
    parts = [BANNER]
    rules, stills = [], []
    for node_id, (name, role, props) in M.TRACKS.items():
        block, slug, animations = node_rules(node_id, name, role, props)
        parts.append(block)
        shorthand = ",\n    ".join(
            f"{kf} {M.LOOP_SECONDS}s linear infinite" for kf in animations)
        # Everything but the ring starts invisible, so no object flashes in
        # the frame between first paint and the animation's first tick.
        hidden = "" if role == "ring" else "\n  opacity: 0;"
        rules.append(
            f".{PREFIX}-{slug} {{\n  animation:\n    {shorthand};{hidden}\n}}")
        decls = " ".join(still_declarations(node_id, name, role, props))
        stills.append(f"  .{PREFIX}-{slug} {{ animation-name: none; {decls} }}")

    parts.append("/* Element hooks. Each node drives one CSS property per\n"
                 "   track, so the tracks never fight over `transform`. */")
    parts.extend(rules)

    parts.append(
        "/* The global reduced-motion rule in globals.css collapses every\n"
        "   animation onto its 100% frame, which here is the moment after\n"
        "   the fourth phase has left — an empty header. Drop the animations\n"
        "   outright instead and hold the frame Figma itself renders. */\n"
        "@media (prefers-reduced-motion: reduce) {\n"
        + "\n".join(stills) + "\n}")
    return "\n\n".join(parts) + "\n"


def main():
    if not os.path.isdir(SHEETS):
        sys.exit(f"missing {SHEETS} — re-download the Figma sprite sheets first")

    problems = M.validate()
    if problems:
        for line in problems:
            print("FAIL", line)
        sys.exit("motion spec is malformed")

    rows, total = build_sprites()
    print("sprites")
    print("\n".join(rows))
    print(f"  {'total':<18} {total:.0f} KB (sheets were ~2.5 MB)\n")

    os.makedirs(os.path.dirname(SPEC_OUT), exist_ok=True)
    spec = build_spec()
    with open(SPEC_OUT, "w", encoding="utf-8") as fh:
        fh.write(spec)
    print(f"wrote {os.path.relpath(SPEC_OUT, ROOT)} ({len(spec):,} chars)")

    css = build_css()
    with open(CSS_OUT, "w", encoding="utf-8") as fh:
        fh.write(css)
    print(f"wrote {os.path.relpath(CSS_OUT, ROOT)} ({len(css):,} chars, "
          f"{css.count('@keyframes')} keyframe rules)")


main()
