#!/usr/bin/env python3
"""
Extracts brand assets from the MB Design System (Mozaic) reference files into
typed React components.

Assets are never hand-authored or approximated — they are lifted verbatim from
`references/{logos,icons,illustrations}.md` so the committed components stay
byte-faithful to the design system. Extend `mozaic-assets.json` as each Figma
section calls for an asset, then re-run.

Usage:
    MB_SKILL_DIR=/path/to/skills/mb-design-system python3 scripts/extract-mozaic-assets.py
"""

import json
import os
import re
import sys

SKILL = os.environ.get("MB_SKILL_DIR")
if not SKILL:
    sys.exit("MB_SKILL_DIR must point at the mb-design-system skill directory")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REFS = os.path.join(SKILL, "references")
OUT = os.path.join(ROOT, "src", "components")

GRAY_900 = "#252D38"

with open(os.path.join(HERE, "mozaic-assets.json"), encoding="utf-8") as fh:
    MANIFEST = json.load(fh)


def parse(filename):
    """Map every `### Name` heading in a reference file to its SVG source."""
    with open(os.path.join(REFS, filename), encoding="utf-8") as fh:
        text = fh.read()
    found = re.findall(r"^### (.+?)\n(.*?)```svg\n(.*?)\n```", text, re.S | re.M)
    return {name.strip(): svg for name, _meta, svg in found}


def jsxify(svg):
    """Convert raw SVG markup to JSX-safe attribute casing."""
    for svg_attr, jsx_attr in (
        ("stroke-width", "strokeWidth"),
        ("stroke-linecap", "strokeLinecap"),
        ("stroke-linejoin", "strokeLinejoin"),
        ("stroke-miterlimit", "strokeMiterlimit"),
        ("stroke-dasharray", "strokeDasharray"),
        ("stroke-opacity", "strokeOpacity"),
        ("fill-opacity", "fillOpacity"),
        ("fill-rule", "fillRule"),
        ("clip-rule", "clipRule"),
        ("clip-path", "clipPath"),
        ("stop-color", "stopColor"),
        ("stop-opacity", "stopOpacity"),
        ("xlink:href", "xlinkHref"),
        ("xmlns:xlink", "xmlnsXlink"),
        ("data-name", "dataName"),
        ("class=", "className="),
    ):
        svg = svg.replace(svg_attr, jsx_attr)
    return svg


def inner(svg):
    """Strip the outer <svg> wrapper, keeping only its children."""
    return re.sub(r"^<svg[^>]*>\s*|\s*</svg>\s*$", "", svg.strip(), flags=re.S)


def viewbox(svg):
    match = re.search(r'viewBox="([^"]+)"', svg)
    return match.group(1) if match else "0 0 24 24"


def namespace_ids(svg, prefix):
    """Rewrite every id/url reference so multiple assets can coexist on a page."""
    ids = set(re.findall(r'\sid="([^"]+)"', svg))
    for raw in sorted(ids, key=len, reverse=True):
        safe = f"{prefix}-{raw}"
        svg = svg.replace(f'id="{raw}"', f'id="{safe}"')
        svg = svg.replace(f"url(#{raw})", f"url(#{safe})")
        svg = svg.replace(f'xlinkHref="#{raw}"', f'xlinkHref="#{safe}"')
    return svg


def slug(component):
    """Short, stable id prefix derived from the component name."""
    return re.sub(r"[^a-z0-9]", "", component.lower())[:12]


def indent(body):
    return "\n".join("      " + line for line in body.splitlines())


HEADER = (
    "// AUTO-GENERATED by scripts/extract-mozaic-assets.py — do not edit by hand.\n"
    "// Source: MB Design System (Mozaic) {source}\n"
    "// Add assets via scripts/mozaic-assets.json, then re-run the script.\n"
)


def require(available, wanted, kind):
    missing = [name for name in wanted if name not in available]
    if missing:
        sys.exit(f"{kind} absent from the reference file: {', '.join(missing)}")


# --------------------------------------------------------------------------
# Logos
# --------------------------------------------------------------------------

def logo_component(svg, component):
    """Emit one logo component with its class-based fills inlined.

    The reference logos carry a <defs><style> block scoping `.cls-N` fills.
    Inlining those keeps the mark's colours exact while removing a global
    style block that would otherwise leak and collide between instances.
    """
    body = inner(jsxify(svg))
    fills = dict(re.findall(r"\.(cls-\d+)\s*\{\s*fill:\s*(#[0-9a-fA-F]+);", body))
    body = re.sub(r"<defs>.*?</defs>", "", body, flags=re.S).strip()
    for cls, colour in fills.items():
        body = body.replace(f'className="{cls}"', f'fill="{colour}"')

    leftover = re.findall(r'className="(cls-\d+)"', body)
    if leftover:
        sys.exit(f"{component}: unresolved logo fill classes {set(leftover)}")

    return f"""
export function {component}({{ className }}: {{ className?: string }}) {{
  return (
    <svg
      viewBox="{viewbox(svg)}"
      role="img"
      aria-label="MediBuddy"
      className={{className}}
      xmlns="http://www.w3.org/2000/svg"
    >
{indent(namespace_ids(body, slug(component)))}
    </svg>
  );
}}
"""


def build_logos():
    wanted = MANIFEST.get("logos", {})
    if not wanted:
        return None
    available = parse("logos.md")
    require(available, wanted, "Logos")
    return HEADER.format(source="logos.md") + "".join(
        logo_component(available[name], component)
        for name, component in wanted.items()
    )


# --------------------------------------------------------------------------
# Icons
# --------------------------------------------------------------------------

ICON_PREAMBLE = """
export type IconProps = {
  className?: string;
  /** Icons are decorative by default; pass a label to expose them to AT. */
  label?: string;
};

function iconAria(label?: string) {
  return label
    ? ({ role: "img" as const, "aria-label": label })
    : ({ "aria-hidden": true as const, focusable: false as const });
}
"""


def build_icons():
    wanted = MANIFEST.get("icons", {})
    if not wanted:
        return None
    available = parse("icons.md")
    require(available, wanted, "Icons")

    parts = [HEADER.format(source="icons.md"), ICON_PREAMBLE]
    for name, component in wanted.items():
        svg = available[name]
        # The reference bakes in Gray-900; currentColor lets each usage inherit
        # a semantic token instead. Explicitly sanctioned by icons.md.
        body = inner(jsxify(svg))
        body = body.replace(GRAY_900, "currentColor").replace(
            GRAY_900.lower(), "currentColor"
        )
        parts.append(
            f"""
export function {component}({{ className, label }}: IconProps) {{
  return (
    <svg
      viewBox="{viewbox(svg)}"
      fill="none"
      className={{className}}
      xmlns="http://www.w3.org/2000/svg"
      {{...iconAria(label)}}
    >
{indent(body)}
    </svg>
  );
}}
"""
        )
    return "".join(parts)


# --------------------------------------------------------------------------
# Illustrations
# --------------------------------------------------------------------------

ART_PREAMBLE = """
export type ArtProps = {
  className?: string;
  label?: string;
};
"""


def build_illustrations():
    wanted = MANIFEST.get("illustrations", {})
    if not wanted:
        return None
    available = parse("illustrations.md")
    require(available, wanted, "Illustrations")

    parts = [HEADER.format(source="illustrations.md"), ART_PREAMBLE]
    for name, component in wanted.items():
        svg = available[name]
        body = namespace_ids(inner(jsxify(svg)), slug(component))
        parts.append(
            f"""
export function {component}({{ className, label }}: ArtProps) {{
  return (
    <svg
      viewBox="{viewbox(svg)}"
      className={{className}}
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      {{...(label
        ? {{ role: "img" as const, "aria-label": label }}
        : {{ "aria-hidden": true as const, focusable: false as const }})}}
    >
{indent(body)}
    </svg>
  );
}}
"""
        )
    return "".join(parts)


def write(relative_path, content):
    if content is None:
        print(f"skipped {relative_path} (nothing requested in the manifest)")
        return
    target = os.path.join(OUT, relative_path)
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"wrote {relative_path} ({len(content):,} chars)")


write("brand/logos.tsx", build_logos())
write("icons/index.tsx", build_icons())
write("illustrations/index.tsx", build_illustrations())
