// AUTO-GENERATED by scripts/build-hero-animated.py — do not edit by hand.
// Source: Figma "Health Verse Revamp_Jan25", node 1208:3049 "Header/ Animated".
//
// Every number is in CSS pixels within the 360x367 frame. Figma's frame is
// 360x395; the top 28px is a device status bar, which is not rendered for
// the same reason Header.tsx omits it.

export const FRAME_WIDTH = 360;
export const FRAME_HEIGHT = 367;
export const LOOP_SECONDS = 16;

/** Figma: brand-blue/Gradients - Brand/Dark/900 -> 700 (45deg). */
export const BACKGROUND =
  "linear-gradient(45deg in srgb, #00296a 0%, #004fb6 100%)";

export const RING = {
  left: 34, top: 60, size: 292,
  outer: { r: 141.576, width: 8.84848, opacity: 0.07 },
  inner: { r: 115.252, width: 1.32727, opacity: 0.14 },
  dot: { cx: 146, cy: 4.42424, r: 4.42424, opacity: 0.35 },
} as const;

export const BADGE = {
  left: 89, top: 100, width: 182,
  iconSize: 16, gap: 4,
  text: "MediBuddy Assured",
} as const;

export const HERO_WORD = {
  left: 75, top: 200, width: 209,
  text: "programs",
  shadow: "0 4px 0 #1b1b1b, 0 10px 18px rgb(0 0 0 / 0.35)",
} as const;

export type HeroTag = {
  id: string; text: string; token: string;
  left: number; top: number; width: number; height: number;
};

/** All four are rotated -2 degrees in Figma. */
export const TAG_ROTATION = -2;

export const TAGS: HeroTag[] = [
  { id: "1", text: "GENUINE", token: "yellow-100", left: 90.748, top: 136.092, width: 178, height: 46 },
  { id: "2", text: "AFFORDABLE", token: "success-100", left: 64.733, top: 135.999, width: 230, height: 46 },
  { id: "3", text: "EASY-PAY", token: "warning-100", left: 90.748, top: 135.092, width: 178, height: 46 },
  { id: "4", text: "TRUSTED", token: "pink-100", left: 93.75, top: 136.005, width: 173, height: 46 },
];

export type HeroProof = {
  id: string; text: string;
  left: number; top: number; width: number;
};

export const PROOFS: HeroProof[] = [
  { id: "1", text: "Directly from cult.fit, FITPASS and more", left: 39, top: 267, width: 282 },
  { id: "2", text: "at best prices", left: 132, top: 274, width: 96 },
  { id: "3", text: "pay with UPI, card and wallets", left: 71, top: 266, width: 217 },
  { id: "4", text: "over 12,000+ already joined", left: 81, top: 266, width: 197 },
];

export type HeroObject = {
  id: string; icon: string;
  left: number; top: number; width: number; height: number;
};

/** Listed back-to-front, which is also the order they render in. */
export const OBJECTS: HeroObject[] = [
  { id: "4-1", icon: "award", left: 18, top: 72, width: 58.109, height: 58 },
  { id: "4-2", icon: "shield", left: 292.408, top: 161.408, width: 48, height: 48 },
  { id: "4-3", icon: "verified", left: 36.013, top: 278.917, width: 60, height: 60.776 },
  { id: "4-4", icon: "runner", left: 240.715, top: 312.733, width: 48.091, height: 47.999 },
  { id: "3-4", icon: "shield", left: 259.905, top: 299.905, width: 28, height: 28 },
  { id: "3-2", icon: "check", left: 297.342, top: 154.342, width: 48, height: 48 },
  { id: "3-1", icon: "price-tag", left: 21.319, top: 101.299, width: 60, height: 60 },
  { id: "3-3", icon: "wallet", left: 74.278, top: 305.278, width: 53, height: 53 },
  { id: "2-1", icon: "wallet", left: 36.027, top: 109.157, width: 44, height: 44 },
  { id: "2-2", icon: "price-tag", left: 287.328, top: 83.328, width: 60, height: 60 },
  { id: "2-4", icon: "discount", left: 278.518, top: 275.518, width: 47, height: 47 },
  { id: "2-3", icon: "check", left: 48.1, top: 276.1, width: 48, height: 48 },
  { id: "1-1", icon: "verified", left: 13.605, top: 55.484, width: 75.889, height: 76.87 },
  { id: "1-2", icon: "runner", left: 291.957, top: 102.957, width: 64, height: 64 },
  { id: "1-4", icon: "shield", left: 241.233, top: 312.233, width: 47, height: 47 },
  { id: "1-3", icon: "award", left: 57, top: 297, width: 64, height: 64 },
];
