// AUTO-GENERATED by scripts/build-figma-icons.py — do not edit by hand.
// Source: Figma "Health Verse Revamp_Jan25", faq node 1050:6950.
// Exported SVGs are committed under figma-assets/; re-run the script to rebuild.

export type IconProps = {
  className?: string;
  /** Icons are decorative by default; pass a label to expose them to AT. */
  label?: string;
};

function iconAria(label?: string) {
  return label
    ? ({ role: "img" as const, "aria-label": label })
    : ({ "aria-hidden": true as const, focusable: false as const });
}

export function IconChevronDown({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <g>
      <path d="M6 9L12 15L18 9" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
      </g>
    </svg>
  );
}
