// AUTO-GENERATED by scripts/build-figma-icons.py — do not edit by hand.
// Source: Figma "Health Verse Revamp_Jan25", animated header node 1208:3049.
// Exported SVGs are committed under figma-assets/; re-run the script to rebuild.

export type IconProps = {
  className?: string;
  /** Icons are decorative by default; pass a label to expose them to AT. */
  label?: string;
};

function iconAria(label?: string) {
  return label
    ? ({ role: "img" as const, "aria-label": label })
    : ({ "aria-hidden": true as const, focusable: false as const });
}

export function IconCheckmarkBadge02({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 16 16"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <g>
      <path d="M6.24712 8.58426L7.41571 9.75285L10.045 6.53923M6.24712 3.61775L7.62595 2.46873C7.84263 2.28816 8.15738 2.28816 8.37406 2.46873L9.7529 3.61775L11.7979 3.61775C12.1206 3.61775 12.3822 3.87935 12.3822 4.20205L12.3822 6.24708L13.5312 7.62591C13.7118 7.84259 13.7118 8.15734 13.5312 8.37402L12.3822 9.75285L12.3822 11.7979C12.3822 12.1206 12.1206 12.3822 11.7979 12.3822H9.75289L8.37406 13.5312C8.15738 13.7118 7.84263 13.7118 7.62595 13.5312L6.24712 12.3822L4.20209 12.3822C3.87939 12.3822 3.61779 12.1206 3.61779 11.7979L3.61779 9.75285L2.46877 8.37402C2.2882 8.15734 2.2882 7.84259 2.46877 7.62591L3.61779 6.24708L3.61779 4.20205C3.61779 3.87935 3.87939 3.61775 4.20209 3.61775L6.24712 3.61775Z" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round"/>
      </g>
    </svg>
  );
}
