// AUTO-GENERATED by scripts/build-figma-icons.py — do not edit by hand.
// Source: Figma "Health Verse Revamp_Jan25", how it works node 1050:6818.
// Exported SVGs are committed under figma-assets/; re-run the script to rebuild.

export type IconProps = {
  className?: string;
  /** Icons are decorative by default; pass a label to expose them to AT. */
  label?: string;
};

function iconAria(label?: string) {
  return label
    ? ({ role: "img" as const, "aria-label": label })
    : ({ "aria-hidden": true as const, focusable: false as const });
}

export function IconSearch01({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 32 32"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <g>
      <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M21.1603 21.1611C21.5808 20.7406 22.2625 20.7406 22.6829 21.1611L27.5279 26.0061C27.9484 26.4265 27.9484 27.1082 27.5279 27.5287C27.1075 27.9492 26.4258 27.9492 26.0053 27.5287L21.1603 22.6837C20.7398 22.2632 20.7398 21.5815 21.1603 21.1611Z" fill="currentColor"/>
      <path fillRule="evenodd" clipRule="evenodd" d="M4.15663 14.9241C4.15663 8.97779 8.97703 4.15738 14.9233 4.15738C20.8696 4.15738 25.69 8.97779 25.69 14.9241C25.69 20.8703 20.8696 25.6907 14.9233 25.6907C8.97703 25.6907 4.15663 20.8703 4.15663 14.9241ZM14.9233 6.31072C10.1663 6.31072 6.30996 10.167 6.30996 14.9241C6.30996 19.6811 10.1663 23.5374 14.9233 23.5374C19.6803 23.5374 23.5366 19.6811 23.5366 14.9241C23.5366 10.167 19.6803 6.31072 14.9233 6.31072Z" fill="currentColor"/>
      </g>
      </g>
    </svg>
  );
}

export function IconCouponPercent({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 32 32"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <g>
      <path d="M19.0001 12.9995L13.0001 18.9995M19.0001 18.9995H18.9911M13.0091 12.9995H13.0001M4.00009 8.79948V12.9995C5.65694 12.9995 7.00009 14.3426 7.00009 15.9995C7.00009 17.6563 5.65694 18.9995 4.00009 18.9995V23.1995C4.00009 24.525 5.0746 25.5995 6.40009 25.5995H25.6001C26.9256 25.5995 28.0001 24.525 28.0001 23.1995V18.9995C26.3432 18.9995 25.0001 17.6563 25.0001 15.9995C25.0001 14.3426 26.3432 12.9995 28.0001 12.9995V8.79948C28.0001 7.474 26.9256 6.39948 25.6001 6.39948H6.40009C5.0746 6.39948 4.00009 7.474 4.00009 8.79948Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
      </g>
    </svg>
  );
}

export function IconInvoice01({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 32 32"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <g>
      <path d="M15.4 14.8H11.8M19 10H11.8M25.6 6.4V27.4L20.8 25L16 28L11.2 25L6.4 27.4V6.4C6.4 5.07452 7.47452 4 8.8 4H23.2C24.5255 4 25.6 5.07452 25.6 6.4Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
      </g>
    </svg>
  );
}
