// AUTO-GENERATED by scripts/build-figma-icons.py — do not edit by hand.
// Source: Figma "Health Verse Revamp_Jan25", payment confirmation node 1050:15076.
// Exported SVGs are committed under figma-assets/; re-run the script to rebuild.

export type IconProps = {
  className?: string;
  /** Icons are decorative by default; pass a label to expose them to AT. */
  label?: string;
};

function iconAria(label?: string) {
  return label
    ? ({ role: "img" as const, "aria-label": label })
    : ({ "aria-hidden": true as const, focusable: false as const });
}

export function IconSuccessBadge({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 54.9333 54.4"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <path d="M20.0699 51.3805C13.3965 46.8484 7.62631 41.1339 3.04993 34.525C1.11681 32.5649 0.0239722 29.9403 3.58625e-05 27.2005C-0.0035648 25.8409 0.264004 24.4939 0.787386 23.237C1.31077 21.98 2.07966 20.8378 3.04993 19.8759C7.93257 13.5259 13.6575 7.85678 20.0699 3.02187C22.0488 1.1066 24.6991 0.0237536 27.466 3.64378e-05C28.839 -0.00357652 30.1992 0.261525 31.4684 0.780108C32.7377 1.29869 33.891 2.06053 34.862 3.02187C41.1846 7.95731 46.8974 13.614 51.882 19.8748C53.816 21.8346 54.9094 24.4593 54.9333 27.1994C54.9366 28.5591 54.6688 29.9061 54.1452 31.163C53.6215 32.42 52.8524 33.5621 51.882 34.524C46.9022 40.7897 41.1889 46.4478 34.862 51.3794C33.6018 52.6048 32.0569 53.5046 30.363 53.9998C29.4218 54.2705 28.4461 54.4053 27.466 54.3998C26.2345 54.3721 25.0169 54.1362 23.8658 53.7021C22.4602 53.1798 21.1709 52.3912 20.0699 51.3805Z" fill="var(--color-textcolor-green-700)"/>
    </svg>
  );
}

export function IconCheckmarkCircle02({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 16 16"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <g>
      <path d="M6.08689 7.64645C5.89162 7.45118 5.57504 7.45118 5.37978 7.64645C5.18452 7.84171 5.18452 8.15829 5.37978 8.35355L5.73333 8L6.08689 7.64645ZM7.43333 9.7L7.07978 10.0536C7.17911 10.1529 7.31565 10.2059 7.45599 10.1995C7.59633 10.1931 7.72751 10.128 7.81744 10.0201L7.43333 9.7ZM10.6508 6.62009C10.8276 6.40795 10.7989 6.09267 10.5868 5.91589C10.3746 5.73911 10.0593 5.76777 9.88256 5.97991L10.2667 6.3L10.6508 6.62009ZM13.6667 8H14.1667C14.1667 4.59424 11.4058 1.83333 8 1.83333V2.33333V2.83333C10.8535 2.83333 13.1667 5.14653 13.1667 8H13.6667ZM8 2.33333V1.83333C4.59424 1.83333 1.83333 4.59424 1.83333 8H2.33333H2.83333C2.83333 5.14653 5.14653 2.83333 8 2.83333V2.33333ZM2.33333 8H1.83333C1.83333 11.4058 4.59424 14.1667 8 14.1667V13.6667V13.1667C5.14653 13.1667 2.83333 10.8535 2.83333 8H2.33333ZM8 13.6667V14.1667C11.4058 14.1667 14.1667 11.4058 14.1667 8H13.6667H13.1667C13.1667 10.8535 10.8535 13.1667 8 13.1667V13.6667ZM5.73333 8L5.37978 8.35355L7.07978 10.0536L7.43333 9.7L7.78689 9.34645L6.08689 7.64645L5.73333 8ZM7.43333 9.7L7.81744 10.0201L10.6508 6.62009L10.2667 6.3L9.88256 5.97991L7.04922 9.37991L7.43333 9.7Z" fill="currentColor"/>
      </g>
    </svg>
  );
}

export function IconHelpCircle({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <g>
      <path d="M12 16.05H12.0081M10.2 9.75C10.2 8.75589 11.0059 7.95 12 7.95C12.9941 7.95 13.8 8.75589 13.8 9.75C13.8 10.1083 13.6953 10.4422 13.5148 10.7227C12.9769 11.5587 12 12.3559 12 13.35M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
      </g>
    </svg>
  );
}
