// AUTO-GENERATED by scripts/build-figma-icons.py — do not edit by hand.
// Source: Figma "Health Verse Revamp_Jan25", featured programs node 1050:6683.
// Exported SVGs are committed under figma-assets/; re-run the script to rebuild.

export type IconProps = {
  className?: string;
  /** Icons are decorative by default; pass a label to expose them to AT. */
  label?: string;
};

function iconAria(label?: string) {
  return label
    ? ({ role: "img" as const, "aria-label": label })
    : ({ "aria-hidden": true as const, focusable: false as const });
}

export function IconArrowRight01({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 16 16"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <g>
      <path d="M5.00005 2L11 8L5 14" stroke="#004FB6" strokeWidth="1.33333" strokeMiterlimit="16" strokeLinecap="round" strokeLinejoin="round"/>
      </g>
    </svg>
  );
}
