// AUTO-GENERATED by scripts/build-figma-icons.py — do not edit by hand.
// Source: Figma "Health Verse Revamp_Jan25", track order sheet node 1050:11965.
// Exported SVGs are committed under figma-assets/; re-run the script to rebuild.

export type IconProps = {
  className?: string;
  /** Icons are decorative by default; pass a label to expose them to AT. */
  label?: string;
};

function iconAria(label?: string) {
  return label
    ? ({ role: "img" as const, "aria-label": label })
    : ({ "aria-hidden": true as const, focusable: false as const });
}

export function IconStatusDone({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 16 16"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <g>
      <circle cx="8" cy="8" r="8" fill="var(--color-success-50)"/>
      <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M10.4688 5.97901C10.5845 6.09917 10.5845 6.29399 10.4688 6.41415L7.20951 9.79877C7.0938 9.91893 6.9062 9.91893 6.79049 9.79877L5.30901 8.26031C5.19329 8.14015 5.19329 7.94532 5.30901 7.82516C5.42472 7.705 5.61232 7.705 5.72803 7.82516L7 9.14605L10.0497 5.97901C10.1655 5.85885 10.3531 5.85885 10.4688 5.97901Z" fill="var(--color-textcolor-green-700)"/>
      </g>
      </g>
    </svg>
  );
}

export function IconStatusPending({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 16 16"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <g>
      <circle cx="8" cy="8" r="7.66667" fill="white" stroke="currentColor" strokeWidth="0.666667" strokeLinecap="round" strokeDasharray="3.33 3.33"/>
      </g>
    </svg>
  );
}

export function IconDownload04({ className, label }: IconProps) {
  return (
    <svg
      viewBox="0 0 16 16"
      fill="none"
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      {...iconAria(label)}
    >
      <g>
      <path d="M6.33333 7.83333L8 9.5L9.66667 7.83333M8 2.83333V9.09414M13.3333 11.1667L13.1857 12.0525C13.0785 12.6954 12.5223 13.1667 11.8705 13.1667H4.1295C3.47772 13.1667 2.92146 12.6954 2.81431 12.0525L2.66667 11.1667" stroke="currentColor" strokeWidth="1.66667" strokeLinecap="round" strokeLinejoin="round"/>
      </g>
    </svg>
  );
}
